using FFXIVClientStructs.FFXIV.Component.GUI;

namespace OmenTools.Infos;

public static unsafe partial class InfosOm
{
    public static AtkUnitBase* Inventory                => GetAddonByName("Inventory");
    public static AtkUnitBase* InventoryLarge           => GetAddonByName("InventoryLarge");
    public static AtkUnitBase* InventoryExpansion       => GetAddonByName("InventoryExpansion");
    public static AtkUnitBase* LobbyDKT                 => GetAddonByName("LobbyDKT");
    public static AtkUnitBase* ColorantColoring         => GetAddonByName("ColorantColoring");
    public static AtkUnitBase* Dialogue                 => GetAddonByName("Dialogue");
    public static AtkUnitBase* Shop                     => GetAddonByName("Shop");
    public static AtkUnitBase* SelectString             => GetAddonByName("SelectString");
    public static AtkUnitBase* SelectIconString         => GetAddonByName("SelectIconString");
    public static AtkUnitBase* InputNumeric             => GetAddonByName("InputNumeric");
    public static AtkUnitBase* ChatLog                  => GetAddonByName("ChatLog");
    public static AtkUnitBase* CharaCard                => GetAddonByName("CharaCard");
    public static AtkUnitBase* SelectYesno              => GetAddonByName("SelectYesno");
    public static AtkUnitBase* HousingGoods             => GetAddonByName("HousingGoods");
    public static AtkUnitBase* Materialize              => GetAddonByName("Materialize");
    public static AtkUnitBase* LotteryDaily             => GetAddonByName("LotteryDaily");
    public static AtkUnitBase* MaterializeDialog        => GetAddonByName("MaterializeDialog");
    public static AtkUnitBase* TitleMenu                => GetAddonByName("_TitleMenu");
    public static AtkUnitBase* TitleLogo                => GetAddonByName("_TitleLogo");
    public static AtkUnitBase* MateriaAttach            => GetAddonByName("MateriaAttach");
    public static AtkUnitBase* MateriaAttachDialog      => GetAddonByName("MateriaAttachDialog");
    public static AtkUnitBase* MateriaRetrieveDialog    => GetAddonByName("MateriaRetrieveDialog");
    public static AtkUnitBase* PartyList                => GetAddonByName("_PartyList");
    public static AtkUnitBase* NowLoading               => GetAddonByName("NowLoading");
    public static AtkUnitBase* FadeMiddle               => GetAddonByName("FadeMiddle");
    public static AtkUnitBase* FadeBack                 => GetAddonByName("FadeBack");
    public static AtkUnitBase* Logo                     => GetAddonByName("Logo");
    public static AtkUnitBase* AirShipExplorationResult => GetAddonByName("AirShipExplorationResult");
    public static AtkUnitBase* AirShipExplorationDetail => GetAddonByName("AirShipExplorationDetail");
    public static AtkUnitBase* CompanyCraftSupply       => GetAddonByName("CompanyCraftSupply");
    public static AtkUnitBase* LetterList               => GetAddonByName("LetterList");
    public static AtkUnitBase* ContextMenu              => GetAddonByName("ContextMenu");
    public static AtkUnitBase* LookingForGroup          => GetAddonByName("LookingForGroup");
    public static AtkUnitBase* CharacterInspect         => GetAddonByName("CharacterInspect");
    public static AtkUnitBase* CharaSelectListMenu      => GetAddonByName("_CharaSelectListMenu");
    public static AtkUnitBase* CollectablesShop         => GetAddonByName("CollectablesShop");
    public static AtkUnitBase* ContentsFinder           => GetAddonByName("ContentsFinder");
    public static AtkUnitBase* GrandCompanySupplyReward => GetAddonByName("GrandCompanySupplyReward");
    public static AtkUnitBase* GrandCompanySupplyList   => GetAddonByName("GrandCompanySupplyList");
    public static AtkUnitBase* CharaSelectWorldServer   => GetAddonByName("_CharaSelectWorldServer");
    public static AtkUnitBase* MiragePrismPrismBox      => GetAddonByName("MiragePrismPrismBox");
    public static AtkUnitBase* MiragePrismMiragePlate   => GetAddonByName("MiragePrismMiragePlate");
    public static AtkUnitBase* CabinetWithdraw          => GetAddonByName("CabinetWithdraw");
    public static AtkUnitBase* TargetInfo               => GetAddonByName("_TargetInfo");
    public static AtkUnitBase* TargetInfoMainTarget     => GetAddonByName("_TargetInfoMainTarget");
    public static AtkUnitBase* FocusTargetInfo          => GetAddonByName("_FocusTargetInfo");
    public static AtkUnitBase* Request                  => GetAddonByName("Request");
    public static AtkUnitBase* ContextIconMenu          => GetAddonByName("ContextIconMenu");
    public static AtkUnitBase* BannerParty              => GetAddonByName("BannerParty");
    public static AtkUnitBase* ListIcon                 => GetAddonByName("ListIcon");
    public static AtkUnitBase* Macro                    => GetAddonByName("Macro");
    public static AtkUnitBase* FreeCompanyMember        => GetAddonByName("FreeCompanyMember");
    public static AtkUnitBase* MJICraftSchedule         => GetAddonByName("MJICraftSchedule");
    public static AtkUnitBase* PvpReward                => GetAddonByName("PvpReward");
    public static AtkUnitBase* SubmarinePartsMenu       => GetAddonByName("SubmarinePartsMenu");
    public static AtkUnitBase* ContentsFinderConfirm    => GetAddonByName("ContentsFinderConfirm");
}